name: add-issue-to-project

on:
  workflow_call:
    secrets:
      PAT:
        required: true

jobs:
  assign-issue-to-project:
    runs-on: ubuntu-latest
    name: Assign to Project
    steps:
      - uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/NeuroDesk/projects/9
          github-token: ${{ secrets.PAT }}
